[package]
name = "polars-arrow"
version = "0.17.0"
authors = ["ritchie46 <ritchie46@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Arrow interfaces for Polars DataFrame library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = { package = "arrow2", git = "https://github.com/jorgecarleitao/arrow2", rev = "70562fac652a0dab08b4b7bf3d86d2d808ea98e6", default-features = false }
# arrow = { package = "arrow2", git = "https://github.com/ritchie46/arrow2", branch = "null", default-features = false }
# arrow = { package = "arrow2", version = "0.7", default-features = false }
num = "^0.4"
thiserror = "^1.0"
#base64 = { version = "0.13.0", optional = true }
lazy_static = {version = "1.4", optional = true }

[features]
strings = []
compute = ["arrow/compute"]
extension = ["lazy_static"]